DROP TABLE IF EXISTS suggestion_runs CASCADE;
DROP TABLE IF EXISTS suggestion_jobs CASCADE;
DROP TABLE IF EXISTS feed_posts CASCADE;
DROP TABLE IF EXISTS runs CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
